FROM python:3.10-slim as base

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1 \
    PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1

# Set the working directory to /app
RUN mkdir /app
WORKDIR /app

COPY requirements-web.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
        pip install --no-cache-dir -r requirements-web.txt

COPY web.py /app
COPY .env /app
COPY templates/ /app/templates/

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]


