ARG APP_NAME=newsparser_web
ARG PYTHON_VERSION=3.10.0
ARG POETRY_VERSION=1.5.1

FROM python:3.10-slim as builder

ENV PYTHONDONTWRITEBYTECODE 1 \
    PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1
ENV POETRY_VERSION=$POETRY_VERSION \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

RUN mkdir -p /app
WORKDIR /app

RUN pip install poetry
COPY poetry.lock pyproject.toml /app/
RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --only web --no-root


FROM python:3.10-slim as base

ENV PYTHONDONTWRITEBYTECODE 1 \
    PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1
ENV FLASK_APP=web.py \
    FLASK_DEBUG=0 \
    FLASK_ENV=production
ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
WORKDIR /app

COPY web.py .env newsparser.session ./
COPY templates/ ./templates/

EXPOSE 5000

CMD ["gunicorn","-k","gevent","-w","1","-b","0.0.0.0:5000", "web:app"]


