version: '3.8'

services:
    app:
        container_name: newsparser
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile.app
        networks:
            - newsparser_default
        command: ["python", "main.py"]

    web:
        container_name: web
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - "5000:5000"
        networks:
            - newsparser_default
        healthcheck:
            test: curl --fail http://0.0.0.0:5000 || exit 1
        # command: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
        command: ["gunicorn","-k","eventlet","-b","0.0.0.0:5000", "web:app"]

networks:
    newsparser_default:
        external: true