version: '3.9'

services:
    app:
        container_name: newsparser
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - default
        depends_on:
            - mongodb
            - redis
        command: ["python", "main.py"]

    mongodb:
        image: mongo:latest
        container_name: news_db
        restart: always
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: $DB_USER # change this
        #     MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD  # change this
        #     MONGO_INITDB_DATABASE: 'admin'
        #     DB_NAME: $DB_NAME
        #     DB_USER: $DB_USER
        #     DB_PASSWORD: $DB_PASSWORD
        ports:
            - "27017:27017"
        # expose:
        #     - $DB_PORT
        volumes:
            - ./mongo_data:/data/db
            # - ./mongod.conf:/etc/mongod.conf
            # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        healthcheck:
            test: "echo 'db.runCommand(\"ping\").ok'"
            interval: 5s
            timeout: 5s
            retries: 3
        networks:
            - default
        # command: mongod --config /etc/mongod.conf

    redis: # name used as host 
        image: 'redis:latest'
        container_name: user_db
        restart: always
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=$DB_PASSWORD
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
        volumes:
            - ./redis_data:/var/lib/redis
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - default
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass $DB_PASSWORD

networks:
    default:
        driver: bridge
