[tool.poetry]
name = "newsparser"
version = "0.1.0"
description = "parse news"
authors = ["alexander <as.frantsev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.24.1"
feedparser = "^6.0.10"
Telethon = "^1.29.2"
telethon-cryptg = "^0.0.4"
pymongo = "^4.4.1"
Flask = "^2.3.2"
Scrapy = "^2.10.0"
loguru = "^0.7.0"
python-dotenv-vault = "^0.6.3"
Flask-SocketIO = "^5.3.5"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
